<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 * @copyright   2025 Taxi755. All rights reserved.
 * @license     GNU General Public License version 2 or later
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Content\Administrator\Extension\ContentComponent;
use Joomla\Component\Content\Site\Helper\RouteHelper;

/** @var Joomla\CMS\WebAsset\WebAssetManager $wa */
$wa = $this->document->getWebAssetManager();
$wa->useScript('com_content.articles');

// Create shortcuts to some parameters.
$params  = $this->item->params;
$canEdit = $params->get('access-edit');
$user    = Factory::getUser();
$info    = $params->get('info_block_position', 0);

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (Associations::isEnabled() && $params->get('show_associations'));

// Current date
$currentDate = Factory::getDate();
$isUnpublished = strtotime($this->item->publish_up) > strtotime($currentDate) || (($this->item->publish_down != Factory::getDbo()->getNullDate()) && (strtotime($this->item->publish_down) < strtotime($currentDate)));

?>

<div class="com-content-article item-page taxi755-article<?php echo $this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Article">
    <meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? Factory::getConfig()->get('language') : $this->item->language; ?>">

    <?php if ($isUnpublished) : ?>
        <div class="alert alert-info">
            <span class="icon-info-circle" aria-hidden="true"></span><span class="sr-only"><?php echo Text::_('INFO'); ?></span>
            <?php echo Text::_('JNOTPUBLISHEDYET'); ?>
        </div>
    <?php endif; ?>

    <?php if ($params->get('show_page_heading')) : ?>
        <div class="page-header">
            <h1>
                <?php echo $this->escape($params->get('page_heading')); ?>
            </h1>
        </div>
    <?php endif; ?>

    <?php if (!$this->print) : ?>
        <?php if ($canEdit) : ?>
            <div class="item-edit">
                <?php echo LayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item)); ?>
            </div>
        <?php endif; ?>
    <?php else : ?>
        <?php if ($this->item->state == 0 || $isUnpublished) : ?>
            <div class="alert alert-info">
                <span class="icon-info-circle" aria-hidden="true"></span><span class="sr-only"><?php echo Text::_('INFO'); ?></span>
                <?php echo Text::_('JNOTPUBLISHEDYET'); ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>

    <?php // Content is generated by content plugin event "onContentAfterTitle" ?>
    <?php echo $this->item->event->afterDisplayTitle; ?>

    <?php if ($params->get('show_title') || $params->get('show_author')) : ?>
        <div class="article-header">
            <?php if ($params->get('show_title')) : ?>
                <h1 class="article-title" itemprop="headline">
                    <?php echo $this->escape($this->item->title); ?>
                </h1>
            <?php endif; ?>

            <?php if ($this->item->state == ContentComponent::CONDITION_ARCHIVED) : ?>
                <span class="badge badge-secondary"><?php echo Text::_('JARCHIVED'); ?></span>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
    <?php echo $this->item->event->beforeDisplayContent; ?>

    <?php if (isset($this->item->toc)) : ?>
        <?php echo $this->item->toc; ?>
    <?php endif; ?>

    <div class="article-content" itemprop="articleBody">

        <?php if ($params->get('access-view')) : ?>

            <?php echo LayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>

            <?php if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
                <?php echo LayoutHelper::render('joomla.content.tags', $this->item->tags->itemTags); ?>
            <?php endif; ?>

            <?php // Intro text ?>
            <?php if (!empty($this->item->introtext)) : ?>
                <div class="article-intro">
                    <?php echo $this->item->introtext; ?>
                </div>
            <?php endif; ?>

            <?php // Full text ?>
            <?php if (!empty($this->item->fulltext)) : ?>
                <div class="article-fulltext">
                    <?php echo $this->item->fulltext; ?>
                </div>
            <?php endif; ?>

            <?php if ($info == 1 || $info == 2) : ?>
                <?php echo LayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
                <?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
                    <?php echo LayoutHelper::render('joomla.content.tags', $this->item->tags->itemTags); ?>
                <?php endif; ?>
            <?php endif; ?>

        <?php else : ?>
            <?php echo LayoutHelper::render('joomla.content.intro_image', $this->item); ?>
        <?php endif; ?>

    </div>

    <?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
    <?php echo $this->item->event->afterDisplayContent; ?>

    <?php if ($params->get('show_readmore') && $this->item->readmore) : ?>
        <?php if ($params->get('access-view')) : ?>
            <?php $link = Route::_(RouteHelper::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)); ?>
        <?php else : ?>
            <?php $menu = Factory::getApplication()->getMenu(); ?>
            <?php $active = $menu->getActive(); ?>
            <?php $link = new Uri(Route::_($active->link . '&Itemid=' . $active->id, false)); ?>
            <?php $link->setVar('view', 'login'); ?>
            <?php $link->setVar('return', base64_encode(RouteHelper::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language))); ?>
        <?php endif; ?>

        <div class="article-readmore">
            <a class="btn btn-primary" href="<?php echo $link; ?>" itemprop="url" aria-label="<?php echo Text::_('COM_CONTENT_READ_MORE'); ?> <?php echo $this->escape($this->item->title); ?>">
                <span class="icon-chevron-right" aria-hidden="true"></span>
                <?php echo Text::_('COM_CONTENT_READ_MORE_TITLE'); ?>
            </a>
        </div>

    <?php endif; ?>

    <?php if ($this->item->state == 0 || $isUnpublished) : ?>
</div>
<?php endif; ?>

<div class="item-associations">
    <?php echo LayoutHelper::render('joomla.content.associations', $this->item); ?>
</div>

</div>